from __future__ import annotations

from othello import BLACK, EMPTY, WHITE, Board, Move, other_player


def cell_symbol(value: str) -> str:
    if value == EMPTY:
        return "empty"
    if value == BLACK:
        return "black"
    if value == WHITE:
        return "white"
    raise ValueError(f"invalid cell value: {value}")


def turn_symbol(player: str) -> str:
    return "black" if player == BLACK else "white"


def smv_coord(move: Move) -> str:
    row, col = move
    return f"r{row}c{col}"


def generate_smv(board: Board, turn: str, legal_only: bool = True) -> str:
    legal_moves = set(board.legal_moves(turn))
    moves = sorted(legal_moves) if legal_only else [
        (row, col)
        for row in range(board.size)
        for col in range(board.size)
        if board.get(row, col) == EMPTY
    ]
    move_values = ", ".join(smv_coord(move) for move in moves) or "pass"
    next_turn = other_player(turn)

    lines: list[str] = [
        "-- Generated by smv_export.py",
        "-- This is a one-step transition model for the current Othello position.",
        "MODULE main",
        "VAR",
        "  turn : {black, white};",
        f"  move : {{{move_values}}};",
        "  pass : boolean;",
    ]

    for row in range(board.size):
        for col in range(board.size):
            lines.append(f"  b_{row}_{col} : {{empty, black, white}};")

    lines.extend(
        [
            "ASSIGN",
            f"  init(turn) := {turn_symbol(turn)};",
            f"  next(turn) := {turn_symbol(next_turn)};",
            "  init(pass) := FALSE;",
            f"  next(pass) := {'TRUE' if not moves else 'FALSE'};",
        ]
    )

    for row in range(board.size):
        for col in range(board.size):
            value = cell_symbol(board.get(row, col))
            lines.append(f"  init(b_{row}_{col}) := {value};")
            lines.append(f"  next(b_{row}_{col}) := case")
            for move in moves:
                next_board = board.with_move(turn, move) if move in legal_moves else board
                next_value = cell_symbol(next_board.get(row, col))
                lines.append(f"    move = {smv_coord(move)} : {next_value};")
            lines.append(f"    TRUE : {value};")
            lines.append("  esac;")

    lines.extend(
        [
            "DEFINE",
            f"  size := {board.size};",
            f"  current_player := {turn_symbol(turn)};",
            f"  legal_move_count := {len(moves)};",
        ]
    )
    return "\n".join(lines) + "\n"


def write_smv(path: str, board: Board, turn: str, legal_only: bool = True) -> None:
    with open(path, "w", encoding="utf-8") as file:
        file.write(generate_smv(board, turn, legal_only=legal_only))
